Inventationery/apps/Vendor/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:23:26
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-21 20:52:01
from django.conf.urls import url
from .views import createVendorView
from .views import (VendorListView, DeleteVendorView,
                    updateVendorView, export_csv, export_pdf)

urlpatterns = [
    url(r'^vendor/new/$', createVendorView, name='new'),
    url(r'^vendor/$', VendorListView.as_view(), name='list'),
    url(r'^vendor/delete/(?P<pk>[-\w]+)/$',
        DeleteVendorView.as_view(), name='delete'),
    url(r'^vendor/update/(?P<AccountNum>[-\w]+)/$',
        updateVendorView, name='update'),
    url(r'^vendor/export/cvs/$', export_csv, name='csv'),
    url(r'^vendor/export/pdf/$', export_pdf, name='pdf'),
]

Inventationery/apps/home/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-14 15:29:52
# @Last Modified by:   harmenta
# @Last Modified time: 2015-12-31 13:22:17
from django.conf.urls import url
from .views import Home
urlpatterns = [
    url(r'^$', Home, name='home'),
]

Inventationery/apps/login/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-12-29 23:06:33
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-29 23:07:28
from django.conf.urls import url
from .views import LoginView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': reverse_lazy('login')}, name='logout'),
]

config/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 17:10:00
# @Last Modified by:   Alex
# @Last Modified time: 2016-01-04 15:35:51
"""Inventationery URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from __future__ import unicode_literals
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views import defaults as default_views
from Inventationery.core.views import pdf_view

urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),
    url(r'^', include('Inventationery.apps.login.urls')),
    url(r'^', include('Inventationery.apps.home.urls', namespace='home')),
    url(r'^', include('Inventationery.apps.Vendor.urls', namespace='vendor')),
    url(r'^', include('Inventationery.apps.PurchOrder.urls', namespace='purch')),
    url(r'^', include('Inventationery.apps.Inventory.urls', namespace='inventory')),
    url(r'^', include('Inventationery.apps.Payments.urls', namespace='payment')),
    url(r'^', include('Inventationery.apps.Company.urls', namespace='company')),
    url(r'^', include('Inventationery.apps.Customer.urls', namespace='customer')),
    url(r'^', include('Inventationery.apps.SalesOrder.urls', namespace='sales')),
    url(r'^quick_guide/$', pdf_view, name='guide'),

    url(r'^400/$', default_views.bad_request,
        kwargs={'exception': Exception("Bad Request!")}),
    url(r'^403/$', default_views.permission_denied,
        kwargs={'exception': Exception("Permissin Denied")}),
    url(r'^404/$', default_views.page_not_found,
        kwargs={'exception': Exception("Page not Found")}),
    url(r'^500/$', default_views.server_error),
    #(r'^search/', include('haystack.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Inventationery admin'

Inventationery/apps/Company/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: harmenta
# @Date:   2015-12-24 11:10:51
# @Last Modified by:   harmenta
# @Last Modified time: 2015-12-28 17:10:47
from django.db import models
from Inventationery.core.models import TimeStampedModel
from Inventationery.apps.DirParty.models import DirPartyModel


class CompanyInfoModel(TimeStampedModel):
    LegalEntity = 'LEGE'
    LegalPerson = 'LEGP'
    ForeignCompany = 'FORE'

    CompanyTypeChoices = {
        (LegalEntity, 'Entidad jurídica'),
        (LegalPerson, 'Persona jurídica'),
        (ForeignCompany, 'Companía extranjera'),
    }
    # Table fields
    Description = models.TextField(blank=True, null=True)
    CompanyType = models.CharField(max_length=20, choices=CompanyTypeChoices)
    CoRegNum = models.CharField(max_length=13, blank=True)
    VATNum = models.CharField(max_length=13, blank=True)
    DataArea = models.CharField(max_length=4)
    CompanyImage = models.ImageField(
        upload_to='CompanyInfo', null=True, blank=True, default=None)
    # Relations
    Party = models.OneToOneField(DirPartyModel,
                                 default=None,
                                 related_name='CompanyParty',
                                 null=True,
                                 blank=True)
    # Contact Info
    Phone = models.CharField(max_length=50, blank=True, null=True)
    Fax = models.CharField(max_length=50, blank=True, null=True)
    URL = models.URLField(max_length=100, blank=True, null=True)
    Email = models.EmailField(max_length=100, blank=True, null=True)

    # Address Info
    AddressDescription = models.CharField(max_length=30, blank=True, null=True)
    Purpose = models.CharField(max_length=30, default='NEGOCIO')
    CountryRegionId = models.CharField(max_length=3, default='MEX')
    ZipCode = models.CharField(max_length=5, blank=True, null=True)
    Street = models.CharField(max_length=30, blank=True, null=True)
    StreetNumber = models.PositiveSmallIntegerField(blank=True, null=True)
    BuildingCompliment = models.CharField(max_length=10, blank=True, null=True)
    City = models.CharField(max_length=30, blank=True, null=True)
    State = models.CharField(max_length=30, blank=True, null=True)

    def __unicode__(self):
        return self.Party.NameAlias

Inventationery/apps/login/models.py
from django.db import models

# Create your models here.

Inventationery/apps/Company/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: harmenta
# @Date:   2015-12-24 12:13:37
# @Last Modified by:   harmenta
# @Last Modified time: 2015-12-24 12:16:49
from django import forms
from .models import CompanyInfoModel
from Inventationery.apps.DirParty.models import DirPartyModel
from Inventationery.apps.LogisticsPostalAddress.models import (
    LogisticsPostalAddressModel)
from Inventationery.apps.LogisticsElectronicAddress.models import (
    LogisticsElectronicAddressModel)


class CompanyInfoForm(forms.ModelForm):

    class Meta:
        model = CompanyInfoModel
        fields = '__all__'


# Class: Form for DirPartyModel
# ----------------------------------------------------------------------------
class PartyForm(forms.ModelForm):

    class Meta:
        model = DirPartyModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PartyForm, self).__init__(*args, **kwargs)


# Class: Form for LogisticsPostalAddressModel
# ----------------------------------------------------------------------------
class LogisticsPostalForm(forms.ModelForm):

    class Meta:
        model = LogisticsPostalAddressModel
        fields = '__all__'


# Class: Form for LogisticsElectronicAddressModel
# ----------------------------------------------------------------------------
class LogisticsElectronicForm(forms.ModelForm):

    class Meta:
        model = LogisticsElectronicAddressModel
        fields = '__all__'

Inventationery/apps/Customer/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:22:39
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-28 19:32:30
from django import forms
from .models import CustomerModel
from Inventationery.apps.DirParty.models import DirPartyModel
from Inventationery.apps.LogisticsPostalAddress.models import (
    LogisticsPostalAddressModel)
from Inventationery.apps.LogisticsElectronicAddress.models import (
    LogisticsElectronicAddressModel)


# Class: Form for CustomerModel
# ----------------------------------------------------------------------------
class CustomerForm(forms.ModelForm):

    class Meta:
        model = CustomerModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)
        self.fields['AccountNum'].widget.attrs['readonly'] = True
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['AccountType'].widget.attrs['readonly'] = True

    def clean_sku(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            return instance.AccountNum
        else:
            return self.cleaned_data['AccountNum']


# Class: Form for DirPartyModel
# ----------------------------------------------------------------------------
class PartyForm(forms.ModelForm):

    class Meta:
        model = DirPartyModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PartyForm, self).__init__(*args, **kwargs)


# Class: Form for LogisticsPostalAddressModel
# ----------------------------------------------------------------------------
class LogisticsPostalForm(forms.ModelForm):

    class Meta:
        model = LogisticsPostalAddressModel
        fields = '__all__'


# Class: Form for LogisticsElectronicAddressModel
# ----------------------------------------------------------------------------
class LogisticsElectronicForm(forms.ModelForm):

    class Meta:
        model = LogisticsElectronicAddressModel
        fields = '__all__'

Inventationery/apps/Inventory/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:12:08
# @Last Modified by:   harmenta
# @Last Modified time: 2015-12-28 13:42:23
from django import forms
from .models import (ItemModel, ItemVendorModel,
                     InventoryModel, LocationModel,
                     MovementHistoryModel, EcoResProductModel,
                     OrderHistoryModel)


# Class: Form for ItemModel
# ----------------------------------------------------------------------------
class ItemForm(forms.ModelForm):

    class Meta:
        model = ItemModel
        fields = '__all__'


# Class: Form for ItemVendorModel
# ----------------------------------------------------------------------------
class ItemVendorForm(forms.ModelForm):

    class Meta:
        model = ItemVendorModel
        fields = '__all__'


# Class: Form for LocationModel
# ----------------------------------------------------------------------------
class LocationForm(forms.ModelForm):

    class Meta:
        model = LocationModel
        fields = '__all__'


# Class: Form for LocationModel
# ----------------------------------------------------------------------------
class EcoResProductForm(forms.ModelForm):

    class Meta:
        model = EcoResProductModel
        fields = '__all__'


# Class: Form for InventoryModel
# ----------------------------------------------------------------------------
class InventoryForm(forms.ModelForm):

    class Meta:
        model = InventoryModel
        fields = '__all__'


# Class: Form for MovementHistoryModel
# ----------------------------------------------------------------------------
class MovementHistoryForm(forms.ModelForm):

    class Meta:
        model = MovementHistoryModel
        fields = '__all__'


# Class: Form for OrderHistoryModel
# ----------------------------------------------------------------------------
class OrderHistoryForm(forms.ModelForm):

    class Meta:
        model = OrderHistoryModel
        fields = '__all__'

Inventationery/apps/Payments/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-12-20 22:18:47
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-20 22:20:29
from django import forms
from .models import PaymentModel, PaymModeModel


# Class: Form for Payment
# ----------------------------------------------------------------------------
class PaymentForm(forms.ModelForm):

    class Meta:
        model = PaymentModel
        fields = '__all__'


# Class: Form for Payment Mode
# ----------------------------------------------------------------------------
class PaymModeForm(forms.ModelForm):

    class Meta:
        model = PaymModeModel
        fields = '__all__'

Inventationery/apps/PurchOrder/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:16:42
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-12 11:54:15
from django import forms
from .models import PurchOrderModel, PurchLineModel
# from Inventationery.apps.Inventory.models import LocationModel


class PurchOrderForm(forms.ModelForm):

    """Location = forms.ModelChoiceField(queryset=LocationModel.objects.all(
    ), required=True, help_text="Ubicación de inventario")"""

    def __init__(self, *args, **kwargs):
        super(PurchOrderForm, self).__init__(*args, **kwargs)
        self.fields['PurchStatus'].widget.attrs['readonly'] = True

    class Meta:
        model = PurchOrderModel
        fields = '__all__'


class PurchOrderLinesForm(forms.ModelForm):

    class Meta:
        model = PurchLineModel
        fields = '__all__'

Inventationery/apps/SalesOrder/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:16:42
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-28 20:53:30
from django import forms
from .models import SalesOrderModel, SalesLineModel


class SalesOrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(SalesOrderForm, self).__init__(*args, **kwargs)
        self.fields['SalesStatus'].widget.attrs['readonly'] = True

    class Meta:
        model = SalesOrderModel
        fields = '__all__'


class SalesOrderLinesForm(forms.ModelForm):

    class Meta:
        model = SalesLineModel
        fields = '__all__'

Inventationery/apps/Vendor/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:22:39
# @Last Modified by:   harmenta
# @Last Modified time: 2015-11-23 14:13:37
from django import forms
from .models import VendorModel
from Inventationery.apps.DirParty.models import DirPartyModel
from Inventationery.apps.LogisticsPostalAddress.models import (
    LogisticsPostalAddressModel)
from Inventationery.apps.LogisticsElectronicAddress.models import (
    LogisticsElectronicAddressModel)


# Class: Form for VendorModel
# ----------------------------------------------------------------------------
class VendorForm(forms.ModelForm):

    class Meta:
        model = VendorModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(VendorForm, self).__init__(*args, **kwargs)
        self.fields['AccountNum'].widget.attrs['readonly'] = True
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['AccountType'].widget.attrs['readonly'] = True

    def clean_sku(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            return instance.AccountNum
        else:
            return self.cleaned_data['AccountNum']


# Class: Form for DirPartyModel
# ----------------------------------------------------------------------------
class PartyForm(forms.ModelForm):

    class Meta:
        model = DirPartyModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PartyForm, self).__init__(*args, **kwargs)


# Class: Form for LogisticsPostalAddressModel
# ----------------------------------------------------------------------------
class LogisticsPostalForm(forms.ModelForm):

    class Meta:
        model = LogisticsPostalAddressModel
        fields = '__all__'


# Class: Form for LogisticsElectronicAddressModel
# ----------------------------------------------------------------------------
class LogisticsElectronicForm(forms.ModelForm):

    class Meta:
        model = LogisticsElectronicAddressModel
        fields = '__all__'

Inventationery/apps/login/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-12-29 23:06:32
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-29 23:07:45
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50,
                               widget=forms.TextInput(attrs={
                                   'type': 'password'
                               }))

Inventationery/templates/SalesOrder/CreateSalesOrder.html
{% extends 'SalesOrder/SalesOrder.html' %}
{% load widget_tweaks %}

{% block page_title%}
	<div class="row">
		<div class="col-md-6">
			<h3 class="page_title">Nueva orden de venta</h3>	
		</div>
		<div class="col-md-3">
		</div>
		<div class="col-md-3">
			<button type="submit" class="btn btn-success btn-block">Registrar orden de venta</button>
		</div>
	</div>
{% endblock %}

Inventationery/templates/SalesOrder/DeleteSalesOrder.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
	
	<div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel tile">
            <div class="x_title">
                <h2>Ordenes de venta</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="lnr lnr-chevron-down"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
        	</div>
            <div class="x_content">
                <form action="" method="POST">{% csrf_token %}
				    <h3 class="page_title">Seguro que desea eliminar la orden de venta: <strong>{{ object }}"?</strong></h3>
				    <a href="/sales_orders/" class="btn btn-default">Cancelar</a>
				    <input class="btn btn-danger" type="submit" value="Eliminar" />
				</form>
            </div>
        </div>
    </div>
    
{% endblock %}

Inventationery/templates/SalesOrder/SalesOrderChargedList.html
{% extends 'SalesOrder/SalesOrderList.html' %}

{% block content_title %}
	<h2>órdenes de venta cobradas</h2>	
{% endblock content_title %}

Inventationery/templates/SalesOrder/SalesOrderList.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
	
	<div class="col-md-12 col-sm-12 col-xs-12"> <!-- Sales order list -->
        <div class="x_panel tile">
            <div class="x_title">
            	{% block content_title %}
            		<h2>Todas las órdenes de venta</h2>	
            	{% endblock content_title %}
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="lnr lnr-chevron-down"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
        	</div>
            <div class="x_content table-responsive">
            	<a class='btn btn-purple pull-right' href="{% url "sales:new" %}" title="Crear nueva orden de venta" id="NewCustomerBtn">
					<i class="fa fa-plus"></i> Nueva orden de venta
				</a>
				<div><a href="{% url "sales:csv" %}" class="btn btn-warning" title="Exportar a CSV (Archivo separado por comas)">CSV <i class="fa fa-file-text-o"></i></a>
				<a href="{% url "sales:pdf" %}" target="_blank" class="btn btn-danger" title="Exportar a PDF">PDF <i class="fa fa-file-pdf-o"></i></a></div>
				<table id="SalesOrderListTableId" class="display table table-hover">
				    <thead>
				        <tr>
				            <th>Orden de venta</th>
				            <th>Cuenta de cliente</th>
				            <th>Nombre del cliente</th>
				            <th>Nombre</th>
				            <th>Fecha de la OV</th>
				            <th>Tipo de venta</th>
				            <th>Estado del pedido</th>
				            <th>Pedido</th>
				            <th>Acciones</th>
				        </tr>
				    </thead>
				    <tbody>
				    	{% for order in orders %}
				    		<tr>
					            <td><a href="{% url "sales:update" SalesId=order.SalesId %}" class="btn btn-link btn-xs">{{ order.SalesId }}</a></td>
					            <td><a href="{% url "customer:update" AccountNum=order.Customer %}" class="btn btn-link btn-xs">{{ order.Customer }}</a></td>
					            <td>{{ order.Customer.Party.NameAlias }}</td>
					            <td>{{ order.SalesName }}</td>
					            <td>{{ order.created|date:"d/m/y" }}</td>
					            {% if order.SalesType == 'SO' %}
					            	<td>Orden de venta</td>
				            	{% elif order.SalesType == 'RO' %}
				            		<td>Devolución</td>
					            {% endif %}
					            
					            {% if order.SalesStatus == 'OPE' %}
					            	<td>Abierto</td>
			            		{% elif order.SalesStatus == 'BAC'%}
									<td>Back Order</td>
								{% elif order.SalesStatus == 'RED'%}
									<td>Reducido</td>
								{% elif order.SalesStatus == 'INV'%}
									<td>Facturado</td>
								{% elif order.SalesStatus == 'CAS'%}
									<td>Cobrado</td>
								{% elif order.SalesStatus == 'CAN'%}
									<td>Cancelado</td>
								{% elif order.SalesStatus == 'RCA'%}
									<td>Reducido/Cobrado</td>
					            {% endif %}
					            <td>{{ order.DocumentState }}</td>
					            <td class="text-center">
									<a class='btn btn-info btn-xs' href="{% url "sales:update" SalesId=order.SalesId %}">
										<span class="lnr lnr-pencil"></span> Editar
									</a>
									{% if order.SalesStatus == 'OPE' or order.SalesStatus == 'CAN' %}
										<a href="{% url "sales:delete" pk=order.pk %}" class="btn btn-danger btn-xs">
											<span class="lnr lnr-cross"></span> Eliminar
										</a>
								 	{% endif %}
								</td>
					        </tr>
				    	{% endfor %}
				        
				    </tbody>
				</table>
            </div>
        </div>
    </div>

{% endblock %}

Inventationery/templates/SalesOrder/SalesOrderOpenList.html
{% extends 'SalesOrder/SalesOrderList.html' %}

{% block content_title %}
	<h2>órdenes de compra abiertas</h2>	
{% endblock content_title %}

Inventationery/templates/SalesOrder/SalesOrderRecentList.html
{% extends 'SalesOrder/SalesOrderList.html' %}

{% block content_title %}
	<h2>órdenes de venta recientes</h2>	
{% endblock content_title %}

Inventationery/templates/SalesOrder/SalesOrderSentList.html
{% extends 'SalesOrder/SalesOrderList.html' %}

{% block content_title %}
	<h2>órdenes de venta reducidas</h2>	
{% endblock content_title %}

Inventationery/templates/SalesOrder/UpdateSalesOrder.html
{% extends 'SalesOrder/SalesOrder.html' %}
{% load widget_tweaks %}

{% block page_title%}
	<div class="row">
		<div class="col-md-6 page_title">
			<strong class="btn-blue"><h4>{{ SalesOrder.SalesId }} | &nbsp; </h4></strong>
			<span class="btn-info"> <h5>&nbsp; Última vez modificado: {{ SalesOrder.modified|date:"D d M Y" }} {{ SalesOrder.modified|time:"H:i" }} &nbsp;</h5> </span>
		</div>
		<div class="col-md-2">
			<a href="{% url "sales:delete" pk=SalesOrder.pk %}" class="btn btn-danger btn-block pull-right btn-sm" id="delSalesOrderBtn">
				<i class="fa fa-times"></i> Eliminar
			</a>
		</div>
		<div class="col-md-2">
			<a class='btn btn-purple pull-right btn-block btn-sm' href="{% url "sales:new" %}" title="Crear nueva orden de compra" id="NewVendorBtn">
				<i class="fa fa-plus"></i> Nueva (OC)
			</a>
		</div>
		<div class="col-md-2">
			<button type="submit" class="btn btn-success btn-block pull-right btn-sm"><i class="fa fa-check"></i> Guardar</button>
		</div>
	</div>
{% endblock %}