Inventationery/apps/Company/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: harmenta
# @Date:   2015-12-24 12:42:57
# @Last Modified by:   harmenta
# @Last Modified time: 2015-12-28 16:01:15
from django.conf.urls import url
from .views import CompanyInfoView

urlpatterns = [
    url(r'^company/$', CompanyInfoView, name='data'),
]

Inventationery/apps/Inventory/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:12:26
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-30 20:18:13
from django.conf.urls import url
from .views import (createInventView, InventListView, InventExistingListView,
                    DeleteInventView, updateInventView,
                    export_csv, export_pdf,
                    CreateLocationView, UpdateLocationView,
                    ListLocationView, DeleteLocationView)

urlpatterns = [
    url(r'^Item/new/$', createInventView, name='new'),
    url(r'^Item/$', InventListView.as_view(), name='list'),
    url(r'^Item/Existing/$', InventExistingListView.as_view(), name='list-existing'),
    url(r'^Item/delete/(?P<ItemId>[-\w]+)/$',
        DeleteInventView.as_view(), name='delete'),
    url(r'^Item/update/(?P<ItemId>[-\w]+)/$',
        updateInventView, name='update'),
    url(r'^Item/export/cvs/$', export_csv, name='csv'),
    url(r'^Item/export/pdf/$', export_pdf, name='pdf'),

    url(r'^Location/new/$', CreateLocationView.as_view(), name='new-location'),
    url(r'^Location/$', ListLocationView.as_view(), name='list-location'),
    url(r'^Location/update/(?P<LocationName>[-\w]+)/$',
        UpdateLocationView.as_view(), name='update-location'),
    url(r'^Location/delete/(?P<LocationName>[-\w]+)/$',
        DeleteLocationView.as_view(), name='delete-location'),
]

Inventationery/apps/Payments/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-12-20 22:09:47
# @Last Modified by:   Alex
# @Last Modified time: 2016-01-02 19:10:49
from django.conf.urls import url
from .views import (CreatePaymentView,
                    UpdatePaymentView,
                    DeletePaymentView,
                    CreatePaymModeView,
                    UpdatePaymModeView,
                    DeletePaymModeView,
                    PaymentsView)

urlpatterns = [
    url(r'^payment/new/$', CreatePaymentView.as_view(), name='new-payment'),
    url(r'^payment/update/(?P<pk>[-\w]+)/$',
        UpdatePaymentView.as_view(), name='update-payment'),
    url(r'^payment/delete/(?P<pk>[-\w]+)/$',
        DeletePaymentView.as_view(), name='delete-payment'),

    url(r'^paym_mode/new/$', CreatePaymModeView.as_view(), name='new-paym'),
    url(r'^paym_mode/update/(?P<pk>[-\w]+)/$',
        UpdatePaymModeView.as_view(), name='update-paym'),
    url(r'^paym_mode/delete/(?P<pk>[-\w]+)/$',
        DeletePaymModeView.as_view(), name='delete-paym'),
    url(r'^paym_mode/manage/$',
        PaymentsView, name='manage-paym'),
]

Inventationery/apps/PurchOrder/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:21:37
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-21 22:10:00
from django.conf.urls import url
from .views import (PurchOrderListView,
                    PurchOrderRecentListView,
                    PurchOrderOpenListView,
                    PurchOrderReceivedListView,
                    PurchOrderPaidListView,
                    createPurchOrderView,
                    updatePurchOrderView,
                    DeletePurchOrderView,
                    export_csv, export_pdf)

urlpatterns = [
    url(r'^purch_orders/$', PurchOrderListView.as_view(), name='list'),
    url(r'^purch_orders/recent/$',
        PurchOrderRecentListView.as_view(), name='recent'),
    url(r'^purch_orders/open/$',
        PurchOrderOpenListView.as_view(), name='open'),
    url(r'^purch_orders/received/$',
        PurchOrderReceivedListView.as_view(), name='received'),
    url(r'^purch_orders/paid/$',
        PurchOrderPaidListView.as_view(), name='paid'),
    url(r'^purch_orders/new/$', createPurchOrderView, name='new'),
    url(r'^purch_orders/update/(?P<PurchId>[-\w]+)/$',
        updatePurchOrderView, name='update'),
    url(r'^purch_orders/delete/(?P<pk>[-\w]+)/$',
        DeletePurchOrderView.as_view(), name='delete'),

    url(r'^purch_orders/export/cvs/$', export_csv, name='csv'),
    url(r'^purch_orders/export/pdf/$', export_pdf, name='pdf'),
]

Inventationery/apps/Vendor/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:23:26
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-21 20:52:01
from django.conf.urls import url
from .views import createVendorView
from .views import (VendorListView, DeleteVendorView,
                    updateVendorView, export_csv, export_pdf)

urlpatterns = [
    url(r'^vendor/new/$', createVendorView, name='new'),
    url(r'^vendor/$', VendorListView.as_view(), name='list'),
    url(r'^vendor/delete/(?P<pk>[-\w]+)/$',
        DeleteVendorView.as_view(), name='delete'),
    url(r'^vendor/update/(?P<AccountNum>[-\w]+)/$',
        updateVendorView, name='update'),
    url(r'^vendor/export/cvs/$', export_csv, name='csv'),
    url(r'^vendor/export/pdf/$', export_pdf, name='pdf'),
]

Inventationery/apps/home/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-14 15:29:52
# @Last Modified by:   harmenta
# @Last Modified time: 2015-12-31 13:22:17
from django.conf.urls import url
from .views import Home
urlpatterns = [
    url(r'^$', Home, name='home'),
]

Inventationery/apps/login/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-12-29 23:06:33
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-29 23:07:28
from django.conf.urls import url
from .views import LoginView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': reverse_lazy('login')}, name='logout'),
]

config/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 17:10:00
# @Last Modified by:   Alex
# @Last Modified time: 2016-01-04 15:35:51
"""Inventationery URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from __future__ import unicode_literals
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views import defaults as default_views
from Inventationery.core.views import pdf_view

urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),
    url(r'^', include('Inventationery.apps.login.urls')),
    url(r'^', include('Inventationery.apps.home.urls', namespace='home')),
    url(r'^', include('Inventationery.apps.Vendor.urls', namespace='vendor')),
    url(r'^', include('Inventationery.apps.PurchOrder.urls', namespace='purch')),
    url(r'^', include('Inventationery.apps.Inventory.urls', namespace='inventory')),
    url(r'^', include('Inventationery.apps.Payments.urls', namespace='payment')),
    url(r'^', include('Inventationery.apps.Company.urls', namespace='company')),
    url(r'^', include('Inventationery.apps.Customer.urls', namespace='customer')),
    url(r'^', include('Inventationery.apps.SalesOrder.urls', namespace='sales')),
    url(r'^quick_guide/$', pdf_view, name='guide'),

    url(r'^400/$', default_views.bad_request,
        kwargs={'exception': Exception("Bad Request!")}),
    url(r'^403/$', default_views.permission_denied,
        kwargs={'exception': Exception("Permissin Denied")}),
    url(r'^404/$', default_views.page_not_found,
        kwargs={'exception': Exception("Page not Found")}),
    url(r'^500/$', default_views.server_error),
    #(r'^search/', include('haystack.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Inventationery admin'

Inventationery/apps/login/models.py
from django.db import models

# Create your models here.

Inventationery/apps/Company/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: harmenta
# @Date:   2015-12-24 12:13:37
# @Last Modified by:   harmenta
# @Last Modified time: 2015-12-24 12:16:49
from django import forms
from .models import CompanyInfoModel
from Inventationery.apps.DirParty.models import DirPartyModel
from Inventationery.apps.LogisticsPostalAddress.models import (
    LogisticsPostalAddressModel)
from Inventationery.apps.LogisticsElectronicAddress.models import (
    LogisticsElectronicAddressModel)


class CompanyInfoForm(forms.ModelForm):

    class Meta:
        model = CompanyInfoModel
        fields = '__all__'


# Class: Form for DirPartyModel
# ----------------------------------------------------------------------------
class PartyForm(forms.ModelForm):

    class Meta:
        model = DirPartyModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PartyForm, self).__init__(*args, **kwargs)


# Class: Form for LogisticsPostalAddressModel
# ----------------------------------------------------------------------------
class LogisticsPostalForm(forms.ModelForm):

    class Meta:
        model = LogisticsPostalAddressModel
        fields = '__all__'


# Class: Form for LogisticsElectronicAddressModel
# ----------------------------------------------------------------------------
class LogisticsElectronicForm(forms.ModelForm):

    class Meta:
        model = LogisticsElectronicAddressModel
        fields = '__all__'

Inventationery/apps/Customer/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:22:39
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-28 19:32:30
from django import forms
from .models import CustomerModel
from Inventationery.apps.DirParty.models import DirPartyModel
from Inventationery.apps.LogisticsPostalAddress.models import (
    LogisticsPostalAddressModel)
from Inventationery.apps.LogisticsElectronicAddress.models import (
    LogisticsElectronicAddressModel)


# Class: Form for CustomerModel
# ----------------------------------------------------------------------------
class CustomerForm(forms.ModelForm):

    class Meta:
        model = CustomerModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)
        self.fields['AccountNum'].widget.attrs['readonly'] = True
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['AccountType'].widget.attrs['readonly'] = True

    def clean_sku(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            return instance.AccountNum
        else:
            return self.cleaned_data['AccountNum']


# Class: Form for DirPartyModel
# ----------------------------------------------------------------------------
class PartyForm(forms.ModelForm):

    class Meta:
        model = DirPartyModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PartyForm, self).__init__(*args, **kwargs)


# Class: Form for LogisticsPostalAddressModel
# ----------------------------------------------------------------------------
class LogisticsPostalForm(forms.ModelForm):

    class Meta:
        model = LogisticsPostalAddressModel
        fields = '__all__'


# Class: Form for LogisticsElectronicAddressModel
# ----------------------------------------------------------------------------
class LogisticsElectronicForm(forms.ModelForm):

    class Meta:
        model = LogisticsElectronicAddressModel
        fields = '__all__'

Inventationery/apps/Inventory/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:12:08
# @Last Modified by:   harmenta
# @Last Modified time: 2015-12-28 13:42:23
from django import forms
from .models import (ItemModel, ItemVendorModel,
                     InventoryModel, LocationModel,
                     MovementHistoryModel, EcoResProductModel,
                     OrderHistoryModel)


# Class: Form for ItemModel
# ----------------------------------------------------------------------------
class ItemForm(forms.ModelForm):

    class Meta:
        model = ItemModel
        fields = '__all__'


# Class: Form for ItemVendorModel
# ----------------------------------------------------------------------------
class ItemVendorForm(forms.ModelForm):

    class Meta:
        model = ItemVendorModel
        fields = '__all__'


# Class: Form for LocationModel
# ----------------------------------------------------------------------------
class LocationForm(forms.ModelForm):

    class Meta:
        model = LocationModel
        fields = '__all__'


# Class: Form for LocationModel
# ----------------------------------------------------------------------------
class EcoResProductForm(forms.ModelForm):

    class Meta:
        model = EcoResProductModel
        fields = '__all__'


# Class: Form for InventoryModel
# ----------------------------------------------------------------------------
class InventoryForm(forms.ModelForm):

    class Meta:
        model = InventoryModel
        fields = '__all__'


# Class: Form for MovementHistoryModel
# ----------------------------------------------------------------------------
class MovementHistoryForm(forms.ModelForm):

    class Meta:
        model = MovementHistoryModel
        fields = '__all__'


# Class: Form for OrderHistoryModel
# ----------------------------------------------------------------------------
class OrderHistoryForm(forms.ModelForm):

    class Meta:
        model = OrderHistoryModel
        fields = '__all__'

Inventationery/apps/Payments/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-12-20 22:18:47
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-20 22:20:29
from django import forms
from .models import PaymentModel, PaymModeModel


# Class: Form for Payment
# ----------------------------------------------------------------------------
class PaymentForm(forms.ModelForm):

    class Meta:
        model = PaymentModel
        fields = '__all__'


# Class: Form for Payment Mode
# ----------------------------------------------------------------------------
class PaymModeForm(forms.ModelForm):

    class Meta:
        model = PaymModeModel
        fields = '__all__'

Inventationery/apps/PurchOrder/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:16:42
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-12 11:54:15
from django import forms
from .models import PurchOrderModel, PurchLineModel
# from Inventationery.apps.Inventory.models import LocationModel


class PurchOrderForm(forms.ModelForm):

    """Location = forms.ModelChoiceField(queryset=LocationModel.objects.all(
    ), required=True, help_text="Ubicación de inventario")"""

    def __init__(self, *args, **kwargs):
        super(PurchOrderForm, self).__init__(*args, **kwargs)
        self.fields['PurchStatus'].widget.attrs['readonly'] = True

    class Meta:
        model = PurchOrderModel
        fields = '__all__'


class PurchOrderLinesForm(forms.ModelForm):

    class Meta:
        model = PurchLineModel
        fields = '__all__'

Inventationery/apps/SalesOrder/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:16:42
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-28 20:53:30
from django import forms
from .models import SalesOrderModel, SalesLineModel


class SalesOrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(SalesOrderForm, self).__init__(*args, **kwargs)
        self.fields['SalesStatus'].widget.attrs['readonly'] = True

    class Meta:
        model = SalesOrderModel
        fields = '__all__'


class SalesOrderLinesForm(forms.ModelForm):

    class Meta:
        model = SalesLineModel
        fields = '__all__'

Inventationery/apps/login/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-12-29 23:06:32
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-29 23:07:45
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50,
                               widget=forms.TextInput(attrs={
                                   'type': 'password'
                               }))

Inventationery/templates/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>{% block title %} Inventationery {% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static "img/Chart_logo.png" %}" />
    {% block css %}
	<!-- Latest compiled and minified CSS Bootstrap -->
	<link rel="stylesheet" href="{% static "third-party/bootstrap-3.3.5-dist/css/bootstrap.min.css" %}">
	<!-- Font awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Linear icons -->
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
    <!-- Google Fonts -->
    <!-- Open sans -->
    <link href='https://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
    <!-- Source sans -->
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
    <!-- Animate CSS -->
    <link rel="stylesheet" href="{% static "third-party/animate.css/css/animate.min.css" %}">
    <!-- DataTables CSS -->
    <link rel="stylesheet" href="{% static "third-party/DataTables-1.10.10/css/jquery.dataTables.min.css" %}">
    <!-- BoostrapDatePicker CSS -->
    <link rel="stylesheet" href="{% static "third-party/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" %}">
    <!-- SweetAlert CSS -->
    <link rel="stylesheet" href="{% static "third-party/sweet-alert/css/sweetalert.css" %}">
    <!-- SweetAlert CSS -->
    <link rel="stylesheet" href="{% static "third-party/offline/css/offline.css" %}">
    <!-- Base CSS -->
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    {% endblock %}
</head>
<body class="nav-md">

	<div class="container body">
    
        <div class="main_container">

            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">

                    <div class="navbar nav_title" style="border: 0;">
                        <a href="{% url "home:home" %}" class="site_title">
                        	<span>
	                        	<img width="40px" src="{% static "img/svg/doughnut_chart.svg" %}">
	                        	<img height="10px" width="140px" src="{% static "img/Inventationery_title_b.png" %}">
                        	</span>
                    	</a>
                    </div>
                    <div class="clearfix"></div>


                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <ul class="nav side-menu">
                                <li><a class="collapse-menu"> <i class="fa fa-list-alt"></i> Cuentas por pagar <span class="lnr lnr-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none">
                                        <li><a href="{% url "vendor:list" %}"><i class="fa fa-users"></i>Proveedores</a></li>
                                        <li><a href="{% url "purch:list" %}"><i class="fa fa-list-alt"></i>Ordenes de compra (OC)</a></li>
                                        <li><a href="{% url "purch:recent" %}"><i class="fa fa-calendar"></i>(OC) recientes</a></li>
                                        <li><a href="{% url "purch:open" %}"><i class="fa fa-circle-o-notch"></i>(OC) abiertas</a></li>
                                        <li><a href="{% url "purch:received" %}"><i class="fa fa-check"></i>(OC) recibidas</a></li>
                                        <li><a href="{% url "purch:paid" %}"><i class="fa fa-money"></i>(OC) pagadas</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <ul class="nav side-menu">
                                <li><a class="collapse-menu"><i class="fa fa-money"></i> Cuentas por cobrar <span class="lnr lnr-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none">
                                        <li><a href="{% url "customer:list" %}"><i class="fa fa-users"></i>Clientes</a></li>
                                        <li><a href="{% url "sales:list" %}"><i class="fa fa-list-alt"></i>Ordenes de venta (OV)</a></li>
                                        <li><a href="{% url "sales:recent" %}"><i class="fa fa-calendar"></i>(OV) recientes</a></li>
                                        <li><a href="{% url "sales:open" %}"><i class="fa fa-circle-o-notch"></i>(OV) abiertas</a></li>
                                        <li><a href="{% url "sales:sent" %}"><i class="fa fa-check"></i>(OV) enviadas</a></li>
                                        <li><a href="{% url "sales:charged" %}"><i class="fa fa-money"></i>(OV) cobradas</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <ul class="nav">
                                <li><a href="{% url "payment:manage-paym" %}"><i class="fa fa-credit-card-alt"></i>Pago</a></li>
                            </ul>
                            <ul class="nav side-menu">
                                <li><a class="collapse-menu"> <i class="fa fa-cubes"></i> Inventario <span class="lnr lnr-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none">
                                        <li><a href="{% url "inventory:list" %}"><i class="fa fa-database"></i>Artículos</a></li>
                                        <li><a href="{% url "inventory:list-existing" %}"><i class="fa fa-archive"></i>Artículos en existencia</a></li>
                                        <li><a href="{% url "inventory:list-location" %}"><i class="fa fa-location-arrow"></i>Ubicación</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <ul class="nav side-menu">
                                <li><a class="collapse-menu"> <i class="fa fa-building-o"></i> Empresa <span class="lnr lnr-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none">
                                        <li><a href="{% url "company:data" %}"><i class="fa fa-building"></i>Empresa</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>

                    </div>

                </div>
            </div>
            
            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav role="navigation">
                        <div class="row">
                            <div class="col-lg-1 col-md-1 col-sm-2 col-xs-2">
                                <div class="nav toggle">
                                    <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                                </div>
                            </div>
                            <div class="col-lg-5 col-md-5 col-sm-8 col-xs-8">
                                <form style="display:none;">
                                    <div class="inner-addon left-addon">
                                        <span class="lnr lnr-magnifier"></span>
                                        <input id="search-input" type="search" placeholder="Buscar..." class="form-control">
                                    </div>
                                </form>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-2 col-xs-2">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="">
                                        <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                            <img src="{% static "img/dummy.png" %} " alt="">
                                            <span>{{ user.get_username }}</span>
                                            <span class=" fa fa-angle-down"></span>
                                        </a>
                                        <ul class="dropdown-menu dropdown-usermenu animated fadeIn pull-right">
                                            <li><a href="/admin/auth/user/">Perfil<i class="lnr lnr-user pull-right"></i></a>
                                            </li>
                                            <li>
                                                <a href="{% url "admin:index" %}">
                                                    <i class="lnr lnr-cog pull-right"></i>Configuración
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{% url "guide" %}" target="_blank">Ayuda <i class="lnr lnr-question-circle pull-right"></i></a>
                                            </li>
                                            <li class="divider"></li>
                                            <li><a href="{% url 'django.contrib.auth.views.logout' %}" style="color: #F64747;">Salir <i class="lnr lnr-cross-circle pull-right"></i></a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        
                        
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">
                <div class="row">
                    <div class="col-md-12">
                        <div id="content">
                            {% block content %}
                            {% endblock %}
                        </div>
                    </div>
                </div>

                <!-- footer content -->
                {% if messages %}
                <ul class="messages" style="visibility:hidden;">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <footer>
                    <div class="">
                        <!-- <p class="pull-right">Inventationery by <a>Alex Armenta</a>.
                        </p> -->
                    </div>
                    <div class="clearfix"></div>
                </footer>
                <!-- /footer content -->
            </div>
            <!-- /page content -->
        </div>

    </div>
    
	<script type="text/javascript" charset="utf-8" src="{% static "third-party/jquery/jquery-2.1.4.min.js" %}"></script>
    <!-- Latest compiled and minified JavaScript -->
	<script type="text/javascript" charset="utf-8" src="{% static "third-party/bootstrap-3.3.5-dist/js/bootstrap.min.js" %}"></script>
    <!-- DataTables -->
    <script type="text/javascript" charset="utf-8" src="{% static "third-party/DataTables-1.10.10/js/jquery.dataTables.min.js" %}"></script>
    <!-- JQuery Formset -->
    <script type="text/javascript" charset="utf-8" src="{% static "third-party/jquery-formset/js/jquery.formset.js" %}"></script>
    <!-- Boostrap datepicker -->
    <script type="text/javascript" charset="utf-8" src="{% static "third-party/bootstrap-datepicker/js/bootstrap-datepicker.min.js" %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static "third-party/bootstrap-datepicker/js/bootstrap-datepicker.es.min.js" %}"></script>
    <!-- SweetAlert -->
    <script type="text/javascript" charset="utf-8" src="{% static "third-party/sweet-alert/js/sweetalert.min.js" %}"></script>
    <!-- Notie JS -->
    <script type="text/javascript" charset="utf-8" src="{% static "third-party/notie/js/notie.js" %}"></script>
    <!-- Notie JS -->
    <script type="text/javascript" charset="utf-8" src="{% static "third-party/offline/js/offline.js" %}"></script>
    
    <!-- Project JS Files -->
    <script type="text/javascript" charset="utf-8" src="{% static "js/script.js" %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static "js/project.js" %}"></script>
    
    {% block ExtraJS %}
    
    {% endblock ExtraJS %}
</body>
</html>