Inventationery/apps/Inventory/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:12:26
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-30 20:18:13
from django.conf.urls import url
from .views import (createInventView, InventListView, InventExistingListView,
                    DeleteInventView, updateInventView,
                    export_csv, export_pdf,
                    CreateLocationView, UpdateLocationView,
                    ListLocationView, DeleteLocationView)

urlpatterns = [
    url(r'^Item/new/$', createInventView, name='new'),
    url(r'^Item/$', InventListView.as_view(), name='list'),
    url(r'^Item/Existing/$', InventExistingListView.as_view(), name='list-existing'),
    url(r'^Item/delete/(?P<ItemId>[-\w]+)/$',
        DeleteInventView.as_view(), name='delete'),
    url(r'^Item/update/(?P<ItemId>[-\w]+)/$',
        updateInventView, name='update'),
    url(r'^Item/export/cvs/$', export_csv, name='csv'),
    url(r'^Item/export/pdf/$', export_pdf, name='pdf'),

    url(r'^Location/new/$', CreateLocationView.as_view(), name='new-location'),
    url(r'^Location/$', ListLocationView.as_view(), name='list-location'),
    url(r'^Location/update/(?P<LocationName>[-\w]+)/$',
        UpdateLocationView.as_view(), name='update-location'),
    url(r'^Location/delete/(?P<LocationName>[-\w]+)/$',
        DeleteLocationView.as_view(), name='delete-location'),
]

Inventationery/apps/Vendor/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:23:26
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-21 20:52:01
from django.conf.urls import url
from .views import createVendorView
from .views import (VendorListView, DeleteVendorView,
                    updateVendorView, export_csv, export_pdf)

urlpatterns = [
    url(r'^vendor/new/$', createVendorView, name='new'),
    url(r'^vendor/$', VendorListView.as_view(), name='list'),
    url(r'^vendor/delete/(?P<pk>[-\w]+)/$',
        DeleteVendorView.as_view(), name='delete'),
    url(r'^vendor/update/(?P<AccountNum>[-\w]+)/$',
        updateVendorView, name='update'),
    url(r'^vendor/export/cvs/$', export_csv, name='csv'),
    url(r'^vendor/export/pdf/$', export_pdf, name='pdf'),
]

Inventationery/apps/home/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-14 15:29:52
# @Last Modified by:   harmenta
# @Last Modified time: 2015-12-31 13:22:17
from django.conf.urls import url
from .views import Home
urlpatterns = [
    url(r'^$', Home, name='home'),
]

Inventationery/apps/login/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-12-29 23:06:33
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-29 23:07:28
from django.conf.urls import url
from .views import LoginView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': reverse_lazy('login')}, name='logout'),
]

config/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 17:10:00
# @Last Modified by:   Alex
# @Last Modified time: 2016-01-04 15:35:51
"""Inventationery URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from __future__ import unicode_literals
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views import defaults as default_views
from Inventationery.core.views import pdf_view

urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),
    url(r'^', include('Inventationery.apps.login.urls')),
    url(r'^', include('Inventationery.apps.home.urls', namespace='home')),
    url(r'^', include('Inventationery.apps.Vendor.urls', namespace='vendor')),
    url(r'^', include('Inventationery.apps.PurchOrder.urls', namespace='purch')),
    url(r'^', include('Inventationery.apps.Inventory.urls', namespace='inventory')),
    url(r'^', include('Inventationery.apps.Payments.urls', namespace='payment')),
    url(r'^', include('Inventationery.apps.Company.urls', namespace='company')),
    url(r'^', include('Inventationery.apps.Customer.urls', namespace='customer')),
    url(r'^', include('Inventationery.apps.SalesOrder.urls', namespace='sales')),
    url(r'^quick_guide/$', pdf_view, name='guide'),

    url(r'^400/$', default_views.bad_request,
        kwargs={'exception': Exception("Bad Request!")}),
    url(r'^403/$', default_views.permission_denied,
        kwargs={'exception': Exception("Permissin Denied")}),
    url(r'^404/$', default_views.page_not_found,
        kwargs={'exception': Exception("Page not Found")}),
    url(r'^500/$', default_views.server_error),
    #(r'^search/', include('haystack.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Inventationery admin'

Inventationery/apps/Inventory/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:10:36
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-30 22:59:51
from django.db.models import Q
from django.db import models
from django.contrib.auth.models import User
from Inventationery.apps.Vendor.models import VendorModel
from Inventationery.core.models import TimeStampedModel


# Class: Model for prduct item
# ----------------------------------------------------------------------------
class ItemModel(TimeStampedModel):

    INSTOCK = 'INS'
    OFFSTOCK = 'OFS'
    SERVICE = 'SER'

    ItemTypes = (
        (INSTOCK, 'En stock'),
        (OFFSTOCK, 'Fuera de stock'),
        (SERVICE, 'Servicio'),
    )

    ItemId = models.CharField(max_length=20, unique=True)
    ItemType = models.CharField(
        max_length=20, null=True, blank=True, choices=ItemTypes)
    ItemName = models.CharField(max_length=50)
    Description = models.TextField(max_length=100, blank=True, null=True)
    PrimaryVendor = models.ForeignKey(
        VendorModel, default=None, blank=True, null=True)
    Price = models.DecimalField(max_digits=10, decimal_places=2)
    # VendorPrice = models.DecimalField(max_digits=10, decimal_places=2)
    ItemImage = models.ImageField(
        upload_to="ItemTable", default=None, blank=True, null=True)

    def __unicode__(self):
        return "{0}".format(self.ItemId)

    # Get sales unit value
    def getSalesUnit(self):
        try:
            return EcoResProductModel.objects.filter(Item=self).get().SalesUnit
        except:
            return ''

    # Get vendor price
    def getPurchUnit(self):
        try:
            return EcoResProductModel.objects.filter(Item=self).get().PurchUnit
        except:
            return ''

    # Get vendor price
    def getPurchPrice(self):
        try:
            return ItemVendorModel.objects.filter(
                Q(Item=self) & Q(Vendor=self.PrimaryVendor)).get().VendorPrice
        except:
            return ''

    # Verify if item is in stock
    def CanDelete(self):
        InventoryItem = InventoryModel.objects.filter(Item=self)
        if InventoryItem:
            return False
        else:
            return True

    # Get item total in stock
    def GetInventoryTotalItems(self):
        total = 0
        items = InventoryModel.objects.filter(Item=self)
        for item in items:
            total += item.Qty
        return total


# Class: Model for product vendors
# ----------------------------------------------------------------------------
class ItemVendorModel(TimeStampedModel):
    Item = models.ForeignKey(ItemModel, default=None, blank=True, null=True)
    Vendor = models.ForeignKey(
        VendorModel, default=None, blank=True, null=True)
    VendorItemId = models.CharField(max_length=20, blank=True, null=True)
    VendorPrice = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True)


# Class: Model for pruduct locations
# ----------------------------------------------------------------------------
class LocationModel(TimeStampedModel):
    LocationName = models.CharField(
        max_length=50, default='Default', unique=True)

    def __unicode__(self):
        return "{0}".format(self.LocationName)

    def GetTotalItems(self):
        qty = 0
        try:
            Inventory = InventoryModel.objects.filter(Location=self)
            for inventory in Inventory:
                qty += inventory.Qty
        except:
            qty = 0

        return qty

    def GetLocationItems(self):
        try:
            Inventory = InventoryModel.objects.filter(Location=self)
        except:
            Inventory = []

        return Inventory


# Class: Model for product vendors
# ----------------------------------------------------------------------------
class EcoResProductModel(TimeStampedModel):
    Item = models.OneToOneField(ItemModel, default=None, blank=True, null=True)
    BarCode = models.CharField(
        max_length=50, default=None, blank=True, null=True)
    DefaultLocation = models.ForeignKey(
        LocationModel, null=True, blank=True, related_name='DefaultLocation')
    LastVendor = models.ForeignKey(
        VendorModel, default=None, blank=True, null=True)
    StdUnit = models.CharField(
        max_length=20, blank=True, null=True, default='pza.')
    SalesUnit = models.CharField(
        max_length=20, blank=True, null=True, default='pza.')
    PurchUnit = models.CharField(
        max_length=20, blank=True, null=True, default='pza.')
    Notes = models.TextField(max_length=100, blank=True, null=True)


# Class: Model for Inventory items
# ----------------------------------------------------------------------------
class InventoryModel(TimeStampedModel):

    Item = models.ForeignKey(ItemModel,
                             default=None,
                             related_name='Item',
                             null=True,
                             blank=True)
    Location = models.ForeignKey(
        LocationModel, null=True, blank=True, related_name='Location')
    Qty = models.IntegerField(default=0, null=True)

    def __unicode__(self):
        return "{0}: {1} en {2}".format(self.Item, self.Qty, self.Location)


# Class: Model for history movements
# ----------------------------------------------------------------------------
class MovementHistoryModel(TimeStampedModel):
    RECEPTION = 'REC'
    ADJUSTMENT = 'AJD'
    PICKED = 'PIC'
    SALE = 'SAL'

    TransactionTypes = (
        (RECEPTION, 'Recepción de producto'),
        (ADJUSTMENT, 'Ajuste de stock'),
        (PICKED, 'Selección'),
        (SALE, 'Venta'),
    )

    Item = models.ForeignKey(ItemModel,
                             default=None,
                             related_name='ItemHistory',
                             null=True,
                             blank=True)
    TransactionType = models.CharField(max_length=30, choices=TransactionTypes)
    Date = models.DateTimeField(null=True, blank=True, auto_now=True)
    Location = models.ForeignKey(
        LocationModel, null=True, blank=True, related_name='LocationHistory')
    Notes = models.TextField(max_length=100, blank=True, null=True)
    Qty = models.IntegerField(default=0, null=True)
    Qty_prev = models.IntegerField(default=0, null=True)
    Qty_after = models.IntegerField(default=0, null=True)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return "{0}: {1} en {2}".format(self.Item, self.Qty, self.Location)


# Class: Model for order movements
# ----------------------------------------------------------------------------
class OrderHistoryModel(TimeStampedModel):
    PURCH = 'PO'
    SALES = 'SO'

    OrderTypes = (
        (PURCH, 'Orden de compra'),
        (SALES, 'Orden de venta'),
    )

    Item = models.ForeignKey(ItemModel,
                             default=None,
                             related_name='OrderHistory',
                             null=True,
                             blank=True)
    Type = models.CharField(max_length=20, choices=OrderTypes)
    DocumentId = models.CharField(max_length=30)
    CustVendName = models.CharField(
        max_length=100, default=None)
    DocumentDate = models.DateField()
    DocumentStatus = models.CharField(max_length=50)
    DocumentTotal = models.DecimalField(
        max_digits=20, decimal_places=2)
    Qty = models.IntegerField(default=0)
    Price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    SubTotal = models.DecimalField(
        max_digits=20, decimal_places=2, default=0.00)

    def __unicode__(self):
        return "{0}: {1} en {2}".format(self.Item, self.Qty, self.DocumentId)

Inventationery/apps/login/models.py
from django.db import models

# Create your models here.

Inventationery/apps/Company/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: harmenta
# @Date:   2015-12-24 12:13:37
# @Last Modified by:   harmenta
# @Last Modified time: 2015-12-24 12:16:49
from django import forms
from .models import CompanyInfoModel
from Inventationery.apps.DirParty.models import DirPartyModel
from Inventationery.apps.LogisticsPostalAddress.models import (
    LogisticsPostalAddressModel)
from Inventationery.apps.LogisticsElectronicAddress.models import (
    LogisticsElectronicAddressModel)


class CompanyInfoForm(forms.ModelForm):

    class Meta:
        model = CompanyInfoModel
        fields = '__all__'


# Class: Form for DirPartyModel
# ----------------------------------------------------------------------------
class PartyForm(forms.ModelForm):

    class Meta:
        model = DirPartyModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PartyForm, self).__init__(*args, **kwargs)


# Class: Form for LogisticsPostalAddressModel
# ----------------------------------------------------------------------------
class LogisticsPostalForm(forms.ModelForm):

    class Meta:
        model = LogisticsPostalAddressModel
        fields = '__all__'


# Class: Form for LogisticsElectronicAddressModel
# ----------------------------------------------------------------------------
class LogisticsElectronicForm(forms.ModelForm):

    class Meta:
        model = LogisticsElectronicAddressModel
        fields = '__all__'

Inventationery/apps/Customer/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-11-16 19:22:39
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-28 19:32:30
from django import forms
from .models import CustomerModel
from Inventationery.apps.DirParty.models import DirPartyModel
from Inventationery.apps.LogisticsPostalAddress.models import (
    LogisticsPostalAddressModel)
from Inventationery.apps.LogisticsElectronicAddress.models import (
    LogisticsElectronicAddressModel)


# Class: Form for CustomerModel
# ----------------------------------------------------------------------------
class CustomerForm(forms.ModelForm):

    class Meta:
        model = CustomerModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)
        self.fields['AccountNum'].widget.attrs['readonly'] = True
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['AccountType'].widget.attrs['readonly'] = True

    def clean_sku(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            return instance.AccountNum
        else:
            return self.cleaned_data['AccountNum']


# Class: Form for DirPartyModel
# ----------------------------------------------------------------------------
class PartyForm(forms.ModelForm):

    class Meta:
        model = DirPartyModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PartyForm, self).__init__(*args, **kwargs)


# Class: Form for LogisticsPostalAddressModel
# ----------------------------------------------------------------------------
class LogisticsPostalForm(forms.ModelForm):

    class Meta:
        model = LogisticsPostalAddressModel
        fields = '__all__'


# Class: Form for LogisticsElectronicAddressModel
# ----------------------------------------------------------------------------
class LogisticsElectronicForm(forms.ModelForm):

    class Meta:
        model = LogisticsElectronicAddressModel
        fields = '__all__'

Inventationery/apps/Payments/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Alex
# @Date:   2015-12-20 22:18:47
# @Last Modified by:   Alex
# @Last Modified time: 2015-12-20 22:20:29
from django import forms
from .models import PaymentModel, PaymModeModel


# Class: Form for Payment
# ----------------------------------------------------------------------------
class PaymentForm(forms.ModelForm):

    class Meta:
        model = PaymentModel
        fields = '__all__'


# Class: Form for Payment Mode
# ----------------------------------------------------------------------------
class PaymModeForm(forms.ModelForm):

    class Meta:
        model = PaymModeModel
        fields = '__all__'

Inventationery/templates/Inventory/CreateInvent.html
{% extends 'Inventory/Inventory.html' %}
{% load widget_tweaks %}

{% block page_title%}
	<div class="row">
		<div class="col-md-6">
			<h3 class="page_title">Nuevo artículo</h3>	
		</div>
		<div class="col-md-3">
		</div>
		<div class="col-md-3">
			<button type="submit" class="btn btn-success btn-block">Registrar artículo</button>
		</div>
	</div>
{% endblock %}

Inventationery/templates/Inventory/CreateLocation.html
{% extends 'Inventory/Location.html' %}
{% load widget_tweaks %}

{% block page_title%}
	<div class="row">
		<div class="col-md-6">
			<h3 class="page_title">Nueva ubicación</h3>	
		</div>
		<div class="col-md-3">
		</div>
		<div class="col-md-3">
			<button type="submit" class="btn btn-success btn-block">Registrar ubicación</button>
		</div>
	</div>
{% endblock %}

Inventationery/templates/Inventory/DeleteInvent.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
	
	<div class="col-md-12 col-sm-12 col-xs-12"> <!-- Vendors list -->
        <div class="x_panel tile">
            <div class="x_title">
                <h2>Artículos</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="lnr lnr-chevron-down"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
        	</div>
            <div class="x_content">
                <form action="" method="POST">{% csrf_token %}
				    <h3 class="page_title">Seguro que desea eliminar el artículo: <strong>{{ object }}"?</strong></h3>
				    <a href="/Item" class="btn btn-default">Cancelar</a>
				    <input class="btn btn-danger" type="submit" value="Eliminar" />
				</form>
            </div>
        </div>
    </div>
    
{% endblock %}

Inventationery/templates/Inventory/InventoryList.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
	
	<div class="col-md-12 col-sm-12 col-xs-12"> <!-- Purch order list -->
        <div class="x_panel tile">
            <div class="x_title">
                <h2>Inventario de artículos</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="lnr lnr-chevron-down"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
        	</div>
            <div class="x_content table-responsive">
            	<a class='btn btn-purple pull-right' href="{% url "inventory:new" %}" title="Agregar nuevo artículo" id="NewItemBtn">
					<i class="fa fa-plus"></i> Nuevo artículo
				</a>
				<div><a href="{% url "inventory:csv" %}" class="btn btn-warning" title="Exportar a CSV (Archivo separado por comas)">CSV <i class="fa fa-file-text-o"></i></a>
				<a href="{% url "inventory:pdf" %}" target="_blank" class="btn btn-danger" title="Exportar a PDF">PDF <i class="fa fa-file-pdf-o"></i></a></div>
				<table id="InventoryListTableId" class="display table table-hover">
				    <thead>
				        <tr>
				            <th>Código de artículo</th>
				            <th>Nombre de artículo</th>
				            <th>Unidad de venta</th>
				            <th>Precio de venta</th>
				            <th>Proveedor principal</th>
				            <th>Unidad de compra</th>
				            <th>Precio de compra</th>
				            <th>En stock</th>
				            <th>Acciones</th>
				        </tr>
				    </thead>
				    <tbody>
				    	{% for item in items %}
				    		<tr>
					            <td>
					            	<a class='btn btn-link btn-xs' href="{% url "inventory:update" ItemId=item.ItemId %}">
										{{ item.ItemId }}
									</a>
								</td>
					            <td>{{ item.ItemName }}</td>
					            <td>{{ item.getSalesUnit }}</td>
					            <td class="amount">{{ item.Price }}</td>
					            <td>
					            {% if item.PrimaryVendor %}
					            	<a class='btn btn-link btn-xs' href="{% url "vendor:update" AccountNum=item.PrimaryVendor %}">
										{{ item.PrimaryVendor }}
									</a>
					            {% endif %}
					            <td>{{ item.getPurchUnit }}</td>
					            <td class="amount">{{ item.getPurchPrice }}</td>
								</td>
								<td {% if item.GetInventoryTotalItems <= 0 %}class="qty btn-danger" {% else %} class="qty btn-success"{% endif %}>
									{{ item.GetInventoryTotalItems }}
								</td>
					            <td class="text-center">
									<a class='btn btn-info btn-xs' href="{% url "inventory:update" ItemId=item.ItemId %}">
										<span class="lnr lnr-pencil"></span> Editar
									</a> 
									{% if item.CanDelete %}
										<a href="{% url "inventory:delete" ItemId=item.ItemId %}" class="btn btn-danger btn-xs">
											<span class="lnr lnr-cross"></span> Eliminar
										</a>
									{% endif %}
								</td>
					        </tr>
				    	{% endfor %}
				        
				    </tbody>
				</table>
            </div>
        </div>
    </div>

{% endblock %}

Inventationery/templates/Inventory/LocationList.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
	
	<div class="col-md-12 col-sm-12 col-xs-12"> <!-- Purch order list -->
        <div class="x_panel tile">
            <div class="x_title">
                <h2>Ubicaciones de inventario</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="lnr lnr-chevron-down"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
        	</div>
            <div class="x_content table-responsive">
            	<a class='btn btn-purple pull-right' href="{% url "inventory:new-location" %}" title="Agregar nueva ubicación" id="NewVendorBtn">
					<i class="fa fa-plus"></i> Nueva ubicación
				</a>
				<div><a href="{% url "inventory:csv" %}" class="btn btn-warning" title="Exportar a CSV (Archivo separado por comas)">CSV <i class="fa fa-file-text-o"></i></a>
				<a href="{% url "inventory:pdf" %}" target="_blank" class="btn btn-danger" title="Exportar a PDF">PDF <i class="fa fa-file-pdf-o"></i></a></div>
				<table id="LocationListTableId" class="display table table-hover">
				    <thead>
				        <tr>
				            <th>Ubicación</th>
				            <th>Activa desde</th>
				            <th>Artículos</th>
				            <th>Acciones</th>
				        </tr>
				    </thead>
				    <tbody>
				    	{% for location in locations %}
				    		<tr>
					            <td>
					            	<a class='btn btn-link btn-xs' href="{% url "inventory:update-location" LocationName=location.LocationName %}">
										{{ location.LocationName }}
									</a>
								</td>
					            <td>{{ location.created }}</td>
					            <td {% if location.GetTotalItems <= 0 %}class="qty btn-danger" {% else %} class="qty btn-success"{% endif %}>
									{{ location.GetTotalItems }}
								</td>
					            <td class="text-center">
									<a class='btn btn-info btn-xs' href="{% url "inventory:update-location" LocationName=location.LocationName %}">
										<span class="lnr lnr-pencil"></span> Editar
									</a> 
									{% if location.GetTotalItems <= 0 %}
										<a href="{% url "inventory:delete-location" LocationName=location.LocationName %}" class="btn btn-danger btn-xs">
											<span class="lnr lnr-cross"></span> Eliminar
										</a>
									{% endif %}
								</td>
					        </tr>
				    	{% endfor %}
				        
				    </tbody>
				</table>
            </div>
        </div>
    </div>

{% endblock %}

Inventationery/templates/Inventory/UpdateInvent.html
{% extends 'Inventory/Inventory.html' %}
{% load widget_tweaks %}

{% block page_title%}
	<div class="row">
		<div class="col-md-6 page_title">
			<strong class="btn-primary"><h4>{{ Item.ItemId }} | &nbsp; </h4></strong>
			<span class="btn-beige"> <h5> &nbsp;Última vez modificado: {{ Item.modified|date:"D d M Y" }} {{ Item.modified|time:"H:i" }} &nbsp;</h5> </span>
		</div>
		<div class="col-md-2">
			<a href="{% url "inventory:delete" ItemId=Item.ItemId %}" class="btn btn-danger btn-block" id="DelInventBtn">
				<i class="fa fa-times"></i> Eliminar
			</a>
		</div>
		<div class="col-md-2">
			<a class='btn btn-purple pull-right btn-block' href="{% url "inventory:new" %}" title="Crear nuevo artículo" id="NewItemBtn">
				<i class="fa fa-plus"></i> Nuevo artículo
			</a>
		</div>
		<div class="col-md-2">
			<button type="submit" class="btn btn-success btn-block pull-right" id="SaveInventBtn"><i class="fa fa-check"></i> Guardar</button>
		</div>
	</div>
{% endblock %}

Inventationery/templates/Inventory/UpdateLocation.html
{% extends 'Inventory/Location.html' %}
{% load widget_tweaks %}

{% block page_title%}
	<div class="row">
		<div class="col-md-6 page_title">
			<strong class="btn-primary"><h4>{{ Location.LocationName }} | &nbsp; </h4></strong>
			<span class="btn-beige"> <h5> &nbsp;Última vez modificado: {{ Location.modified|date:"D d M Y" }} {{ Location.modified|time:"H:i" }} &nbsp;</h5> </span>
		</div>
		{% if Location.GetTotalItems <= 0 %}
			<div class="col-md-2">
				<a href="{% url "inventory:delete-location" LocationName=Location.LocationName %}" class="btn btn-danger btn-block" id="DelLocationBtn">
					<i class="fa fa-times"></i> Eliminar
				</a>
			</div>
		{% endif %}
		
		<div class="col-md-2">
			<a class='btn btn-purple pull-right btn-block' href="{% url "inventory:new" %}" title="Crear nuevo artículo" id="NewLocationBtn">
				<i class="fa fa-plus"></i> Nueva ubicación
			</a>
		</div>
		<div class="col-md-2">
			<button type="submit" class="btn btn-success btn-block pull-right" id="SaveLocationBtn"><i class="fa fa-check"></i> Guardar</button>
		</div>
	</div>
{% endblock %}